# -*- coding: utf-8 -*-
"""MLC 2Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LLTtJWoXXl-aE-zRJM27yW7voY5UGMPm
"""

pip install numpy pandas matplotlib scikit-learn

# Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_breast_cancer

from sklearn.model_selection import (train_test_split,GridSearchCV,cross_val_score)
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import learning_curve

from sklearn.svm import SVC

from sklearn.ensemble import ( RandomForestClassifier, GradientBoostingClassifier, VotingClassifier)

from sklearn.metrics import (accuracy_score,confusion_matrix,classification_report,ConfusionMatrixDisplay,roc_curve,auc)

#Loading the dataset

data = load_breast_cancer()

# Features (inputs)
X = pd.DataFrame(data.data,columns=data.feature_names)

# Target/output
y = data.target
print("Dataset Shape:", X.shape)
print("\nFeature Names:")
print(X.columns)
print("\nFirst 5 rows:")
print(X.head())

print(data.target_names)

#analyze the data
print(X.describe())

#check classes
pd.Series(y).value_counts()

#Plotting
import seaborn as sns

sns.countplot(x=y)
plt.title("Benign Cancer vs Malignant Cancer")
plt.show()

#correlation Heatmap
plt.figure(figsize=(15,10))
sns.heatmap(X.corr(),cmap="magma")
plt.show()

#preprocessing
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

#Run Model
rf=RandomForestClassifier()

svm=SVC(probability=True)

gb=GradientBoostingClassifier()

rf.fit(X_train,y_train)
svm.fit(X_train,y_train)
gb.fit(X_train,y_train)

#Individual Model Accuracy

models={
"Random Forest":rf,
"SVM":svm,
"Gradient Boosting":gb
}

for name,model in models.items():

    pred=model.predict(X_test)
    print(
        name,
        accuracy_score(y_test,pred)
    )

#Ensemble Model

ensemble = VotingClassifier(estimators=[("rf",rf),("svm",svm),("gb",gb)],voting="soft")
ensemble.fit(X_train,y_train)
pred=ensemble.predict(X_test)
print("Ensemble Accuracy:",accuracy_score(y_test,pred))

rf_accuracy=accuracy_score(y_test,rf.predict(X_test))

svm_accuracy=accuracy_score(y_test,svm.predict(X_test))

gb_accuracy=accuracy_score(y_test,gb.predict(X_test))

#model bar
models=["RF","SVM","GB","Ensemble"]

scores=[rf_accuracy,svm_accuracy,gb_accuracy,accuracy_score(y_test,pred)]
plt.bar(models,scores)

plt.title("Model Accuracy Comparison")

plt.show()

hard_model=VotingClassifier(estimators=[("rf",rf),("svm",svm),("gb",gb)],voting="hard")

hard_model.fit(X_train,y_train)

hard_pred=hard_model.predict(X_test)

print("Hard Voting:",accuracy_score(y_test,hard_pred))

print("Soft Voting:",accuracy_score(y_test,pred))

#confusion matrix
ConfusionMatrixDisplay.from_estimator(ensemble,X_test,y_test)
plt.show()

#classification Report
print(classification_report(y_test, pred))

#Feature Importance
importance=rf.feature_importances_

features=X.columns
imp_df=pd.DataFrame({ "Feature":features,"Importance":importance})
imp_df=imp_df.sort_values(by="Importance",ascending=False).head(10)
print(imp_df)

#Saving Results
imp_df.to_csv(
"important_features.csv",
index=False
)

print("Saved")

#Graphical Represtation
plt.figure(figsize=(10,6))
plt.barh(imp_df["Feature"],imp_df["Importance"])
plt.title("Top Important Features")
plt.show()

#Hyperparameter Tuning
params={"C":[0.1,1,10],"kernel":["linear","rbf"]}

grid=GridSearchCV(SVC(),params,cv=5)
grid.fit(X_train,y_train)
print(grid.best_params_)

#cross validation
scores=cross_val_score(ensemble,X,y,cv=5)

print("Mean Accuracy:",scores.mean())

#Learning Curve

train_sizes,train_scores,test_scores=learning_curve(ensemble,X,y,cv=5)

plt.plot(train_sizes,train_scores.mean(axis=1),label="Training")

plt.plot(train_sizes,test_scores.mean(axis=1),label="Validation")

plt.legend()
plt.title("Learning Curve")

plt.show()

#ROC(Receiver Operating Characteristic curve)
probs=ensemble.predict_proba(X_test)[:,1]

fpr,tpr,_=roc_curve(y_test,probs)
roc_auc=auc(fpr,tpr)
plt.plot(fpr,tpr,label="AUC="+str(roc_auc))

plt.legend()
plt.show()

import pickle

pickle.dump(ensemble,open("cancer_model.pkl","wb"))

print("Model Saved")

pickle.dump(
scaler,open("scaler.pkl","wb"))
print("Scaler Saved")

model=pickle.load(
open("cancer_model.pkl","rb"))

sample = X.iloc[[50]]

sample_scaled = scaler.transform(sample)

prediction = model.predict(sample_scaled)

if prediction[0]==1:
    print("Benign")
else:
    print("Malignant")

import random

test_cases=random.sample(range(569),10)
for i in test_cases:

    print( i, "-", data.target_names[y[i]] )
